[versions]
android-plugin = "8.13.0"
androidx-activity = "1.10.1"
androidx-appcompat = "1.7.0"
androidx-compose = "1.8.0" # sync with jetbrains-compose
androidx-constraintlayout = "2.2.1"
androidx-constraintlayout-compose = "1.1.1"
androidx-core = "1.16.0"
androidx-exifinterface = "1.4.1"
androidx-fragment = "1.8.6"
androidx-lifecycle = "2.8.5" # sync with jetbrains-lifecycle
androidx-navigation = "2.9.0"
androidx-recyclerview = "1.4.0"
androidx-swiperefreshlayout = "1.1.0"
androidx-test-ext-junit = "1.2.1"
androidx-test-rules = "1.6.1"
androidx-test-runner = "1.6.2"

androidgifdrawable = "1.2.29"
androidsvg = "1.4"
appdirs = "1.4.0"

buildkonfig = "0.17.1"

dokka = "1.9.20"    # 2.0.0 There is a problem with the version configuration, so I won't upgrade it yet

ffmpegMediaMetadataRetriever = "1.0.19"

google-flexbox = "3.0.0"
google-material = "1.12.0"
gradle-maven-publish-plugin = "0.33.0"

jetbrains-compose = "1.8.0"
jetbrains-lifecycle = "2.8.4"
jetbrains-compose-material-icons-core = "1.7.3"

koin = "4.1.0"

kotlin = "2.1.10" # 2.1.20 version will report an error when sync 'kotlin-project-structure-metadata.json (No such file or directory)', but it does not affect the compilation
kotlinx-atomicfu = "0.27.0" # sync with kotlin
kotlinx-coroutines = "1.10.2"
kotlinx-cover = "0.9.1"
kotlinx-datetime = "0.6.2"
kotlinx-serialization-json = "1.8.1"
#noinspection GradleDependency
ktor2 = "2.3.13"
ktor3 = "3.0.3" # 3.1.0+ Error when publishing packaging obfuscation on desktop platform: 'https://youtrack.jetbrains.com/issue/KTOR-8325/Proguard-cant-find-enclosing-method-attachFor-error-since-3.1.0'
ktor31 = "3.1.3" # https://youtrack.jetbrains.com/issue/KTOR-7934/JS-WASM-fails-with-IllegalStateException-Content-Length-mismatch-on-requesting-gzipped-content

leakcanary = "2.14"

moko-permissions = "0.19.1"
multiplatform-paging = "3.3.0-alpha02-0.5.1"
multiplatform-settings = "1.3.0"

okhttp3 = "4.12.0"
okio = "3.11.0"

panpf-assemblyadapter4 = "4.1.0"
panpf-tools4a = "1.0.0"
panpf-tools4j = "1.0.0"
panpf-tools4k = "1.0.1"
panpf-zoomimage = "1.4.0"

penfeizhou-animation = "3.0.4"

skiko = "0.9.4"    # sync with jetbrains-compose. 'decodes.nonAndroid#supportDecodeRegion()' must be modified

voyager = "1.1.0-beta03"

[libraries]
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "android-plugin" }
gradlePlugin-androidxNavigationSafeArgs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation" }
gradlePlugin-buildkonfig = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "buildkonfig" }
gradlePlugin-jetbrainsCompose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "jetbrains-compose" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-kotlinComposeCompiler = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-kotlinSerialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
gradlePlugin-kotlinxAtomicfu = { module = "org.jetbrains.kotlinx:atomicfu-gradle-plugin", version.ref = "kotlinx-atomicfu" }
gradlePlugin-kotlinxCover = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kotlinx-cover" }
gradlePlugin-mavenPublish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "gradle-maven-publish-plugin" }
#gradlePlugin-dokka = { module = "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin", version.ref = "dokka" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "androidx-appcompat" }
androidx-compose-ui-test-junit4-android = { module = "androidx.compose.ui:ui-test-junit4-android", version.ref = "androidx-compose" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraintlayout-compose" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidx-exifinterface" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }

androidgifdrawable = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "androidgifdrawable" }
androidsvg = { module = "com.caverock:androidsvg-aar", version.ref = "androidsvg" }
appdirs = { module = "net.harawata:appdirs", version.ref = "appdirs" }

multiplatform-paging = { module = "app.cash.paging:paging-compose-common", version.ref = "multiplatform-paging" }

ffmpegMediaMetadataRetriever-core = { module = "com.github.wseemann:FFmpegMediaMetadataRetriever-core", version.ref = "ffmpegMediaMetadataRetriever" }
ffmpegMediaMetadataRetriever-native = { module = "com.github.wseemann:FFmpegMediaMetadataRetriever-native", version.ref = "ffmpegMediaMetadataRetriever" }

google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
google-flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "google-flexbox" }

jetbrains-lifecycle-common = { module = "org.jetbrains.androidx.lifecycle:lifecycle-common", version.ref = "jetbrains-lifecycle" }
jetbrains-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "jetbrains-lifecycle" }
jetbrains-compose-material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "jetbrains-compose-material-icons-core" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
#koin-test-juint4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
#koin-test-android = { module = "io.insert-koin:koin-android-test", version.ref = "koin" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

ktor2-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor2" }
ktor2-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor2" }
ktor2-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor2" }
ktor2-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor2" }
ktor2-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor2" }

ktor3-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor3" }
ktor3-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor3" }
ktor3-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor3" }
ktor3-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor3" }
ktor3-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor3" }
ktor3-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor3" }
ktor3-client-wasmJs = { module = "io.ktor:ktor-client-js-wasm-js", version.ref = "ktor3" }
ktor31-client-wasmJs = { module = "io.ktor:ktor-client-js-wasm-js", version.ref = "ktor31" }
ktor3-serialization-kotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor3" }

leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

moko-permissions = { module = "dev.icerock.moko:permissions-compose", version.ref = "moko-permissions" }
moko-permissions-storage = { module = "dev.icerock.moko:permissions-storage", version.ref = "moko-permissions" }
multiplatformsettings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
#multiplatform-settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatform-settings" }
#multiplatform-settings-observable = { module = "com.russhwolf:multiplatform-settings-make-observable", version.ref = "multiplatform-settings" }

okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }

panpf-assemblyadapter4-pager2 = { module = "io.github.panpf.assemblyadapter4:assemblyadapter-pager2", version.ref = "panpf-assemblyadapter4" }
panpf-assemblyadapter4-recycler = { module = "io.github.panpf.assemblyadapter4:assemblyadapter-recycler", version.ref = "panpf-assemblyadapter4" }
panpf-assemblyadapter4-recycler-paging = { module = "io.github.panpf.assemblyadapter4:assemblyadapter-recycler-paging", version.ref = "panpf-assemblyadapter4" }

panpf-tools4a-activity = { module = "io.github.panpf.tools4a:tools4a-activity-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-device = { module = "io.github.panpf.tools4a:tools4a-device-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-dimen = { module = "io.github.panpf.tools4a:tools4a-dimen-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-display = { module = "io.github.panpf.tools4a:tools4a-display-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-fileprovider = { module = "io.github.panpf.tools4a:tools4a-fileprovider-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-network = { module = "io.github.panpf.tools4a:tools4a-network-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-run = { module = "io.github.panpf.tools4a:tools4a-run-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-test = { module = "io.github.panpf.tools4a:tools4a-test-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-toast = { module = "io.github.panpf.tools4a:tools4a-toast-ktx", version.ref = "panpf-tools4a" }

panpf-tools4j-date = { module = "io.github.panpf.tools4j:tools4j-date-ktx", version.ref = "panpf-tools4j" }
panpf-tools4j-math = { module = "io.github.panpf.tools4j:tools4j-math-ktx", version.ref = "panpf-tools4j" }
panpf-tools4j-io = { module = "io.github.panpf.tools4j:tools4j-io-ktx", version.ref = "panpf-tools4j" }
panpf-tools4j-reflect = { module = "io.github.panpf.tools4j:tools4j-reflect-ktx", version.ref = "panpf-tools4j" }
panpf-tools4j-security = { module = "io.github.panpf.tools4j:tools4j-security-ktx", version.ref = "panpf-tools4j" }

panpf-tools4k = { module = "io.github.panpf.tools4k:tools4k", version.ref = "panpf-tools4k" }

panpf-zoomimage-view = { module = "io.github.panpf.zoomimage:zoomimage-view", version.ref = "panpf-zoomimage" }
panpf-zoomimage-compose = { module = "io.github.panpf.zoomimage:zoomimage-compose", version.ref = "panpf-zoomimage" }

penfeizhou-animation-awebp = { module = "com.github.penfeizhou.android.animation:awebp", version.ref = "penfeizhou-animation" }

skiko = { module = "org.jetbrains.skiko:skiko", version.ref = "skiko" }

voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
#voyager-screenModel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
#voyager-bottomSheetNavigator = { module = "cafe.adriel.voyager:voyager-bottom-sheet-navigator", version.ref = "voyager" }
#voyager-tabNavigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
#voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }
#voyager-hilt = { module = "cafe.adriel.voyager:voyager-hilt", version.ref = "voyager" }
#voyager-kodein = { module = "cafe.adriel.voyager:voyager-kodein", version.ref = "voyager" }
#voyager-rxjava = { module = "cafe.adriel.voyager:voyager-rxjava", version.ref = "voyager" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }