[versions]

# kotlin
kotlin = "1.9.0"
kotlinx-coroutines = "1.7.3"
kotlinx-serialization-json = "1.5.1"

# android
android-plugin = "8.2.0"
androidx-activity = "1.6.1"
androidx-annotation = "1.5.0"
androidx-appcompat = "1.6.0"
androidx-compose = "1.5.0"
androidx-compose-material3 = "1.1.2"
androidx-compose-compiler = "1.5.0"
androidx-constraintlayout = "2.1.4"
androidx-constraintlayout-compose = "1.0.1"
androidx-core = "1.9.0"
androidx-exifinterface = "1.3.5"
androidx-fragment = "1.5.5"
androidx-lifecycle = "2.6.1"
androidx-multidex = "2.0.1"
androidx-navigation = "2.5.3"
androidx-paging = "3.1.1"
androidx-paging-compose = "1.0.0-alpha17"
androidx-palette = "1.0.0"
androidx-recyclerview = "1.2.1"
androidx-swiperefreshlayout = "1.1.0"
androidx-test-runner = "1.5.2"
androidx-test-rules = "1.5.0"
androidx-test-ext-junit = "1.1.5"

# google
google-accompanist = "0.25.1"
google-material = "1.6.1"

# panpf
panpf-activitymonitor = "1.0.0"
panpf-assemblyadapter4 = "4.1.0"
panpf-tools4a = "1.0.0"
panpf-tools4j = "1.0.0"
panpf-tools4k = "1.0.0"
panpf-zoomimage = "1.0.0-beta11"

# other
androidgifdrawable = "1.2.15"
androidsvg = "1.4"
ffmpegMediaMetadataRetriever = "1.0.16"
junit = "4.13.2"
leakcanary = "2.12"
mmkv = "1.2.13"
#noinspection GradleDependency
okhttp3 = "3.12.0"   # 3.12.0 是最后一个支持 Android 5.0 以下的版本
#noinspection GradleDependency
retrofit2 = "2.6.4"
retrofit2-kotlinxSerializationConverter = "0.8.0"
tinypinyin = "2.0.3"
mavenpublish = "0.25.3"
composeStableMarker = "1.0.3"


[libraries]

# kotlin
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

# android
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "androidx-appcompat" }
androidx-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "androidx-compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidx-exifinterface" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "androidx-multidex" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-navigation-safeargsgradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "androidx-paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging-compose" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }
androidx-palette = { module = "androidx.palette:palette", version.ref = "androidx-palette" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }

# google
google-accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "google-accompanist" }
google-accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "google-accompanist" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }

# panpf
panpf-activitymonitor = { module = "io.github.panpf.activitymonitor:activitymonitor", version.ref = "panpf-activitymonitor" }
panpf-assemblyadapter4-pager = { module = "io.github.panpf.assemblyadapter4:assemblyadapter-pager", version.ref = "panpf-assemblyadapter4" }
panpf-assemblyadapter4-pager2 = { module = "io.github.panpf.assemblyadapter4:assemblyadapter-pager2", version.ref = "panpf-assemblyadapter4" }
panpf-assemblyadapter4-recycler = { module = "io.github.panpf.assemblyadapter4:assemblyadapter-recycler", version.ref = "panpf-assemblyadapter4" }
panpf-assemblyadapter4-recycler-paging = { module = "io.github.panpf.assemblyadapter4:assemblyadapter-recycler-paging", version.ref = "panpf-assemblyadapter4" }
panpf-tools4a-activity = { module = "io.github.panpf.tools4a:tools4a-activity-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-device = { module = "io.github.panpf.tools4a:tools4a-device-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-display = { module = "io.github.panpf.tools4a:tools4a-display-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-dimen = { module = "io.github.panpf.tools4a:tools4a-dimen-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-fileprovider = { module = "io.github.panpf.tools4a:tools4a-fileprovider-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-toast = { module = "io.github.panpf.tools4a:tools4a-toast-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-network = { module = "io.github.panpf.tools4a:tools4a-network-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-run = { module = "io.github.panpf.tools4a:tools4a-run-ktx", version.ref = "panpf-tools4a" }
panpf-tools4a-test = { module = "io.github.panpf.tools4a:tools4a-test-ktx", version.ref = "panpf-tools4a" }
panpf-tools4j-math = { module = "io.github.panpf.tools4j:tools4j-math-ktx", version.ref = "panpf-tools4j" }
panpf-tools4j-date = { module = "io.github.panpf.tools4j:tools4j-date-ktx", version.ref = "panpf-tools4j" }
panpf-tools4j-io = { module = "io.github.panpf.tools4j:tools4j-io-ktx", version.ref = "panpf-tools4j" }
panpf-tools4j-test = { module = "io.github.panpf.tools4j:tools4j-test-ktx", version.ref = "panpf-tools4j" }
panpf-tools4j-reflect = { module = "io.github.panpf.tools4j:tools4j-reflect-ktx", version.ref = "panpf-tools4j" }
panpf-tools4j-security = { module = "io.github.panpf.tools4j:tools4j-security-ktx", version.ref = "panpf-tools4j" }
panpf-tools4k = { module = "io.github.panpf.tools4k:tools4k", version.ref = "panpf-tools4k" }
panpf-zoomimage-view-sketch = { module = "io.github.panpf.zoomimage:zoomimage-view-sketch", version.ref = "panpf-zoomimage" }
panpf-zoomimage-compose = { module = "io.github.panpf.zoomimage:zoomimage-compose", version.ref = "panpf-zoomimage" }
panpf-zoomimage-compose-sketch = { module = "io.github.panpf.zoomimage:zoomimage-compose-sketch", version.ref = "panpf-zoomimage" }

# other
androidgifdrawable = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "androidgifdrawable" }
androidsvg = { module = "com.caverock:androidsvg-aar", version.ref = "androidsvg" }
ffmpegMediaMetadataRetriever-core = { module = "com.github.wseemann:FFmpegMediaMetadataRetriever-core", version.ref = "ffmpegMediaMetadataRetriever" }
ffmpegMediaMetadataRetriever-native = { module = "com.github.wseemann:FFmpegMediaMetadataRetriever-native", version.ref = "ffmpegMediaMetadataRetriever" }
junit = { module = "junit:junit", version.ref = "junit" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
okhttp3-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
retrofit2-kotlinxSerializationConverter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2-kotlinxSerializationConverter" }
tinypinyin = { module = "com.github.promeg:tinypinyin", version.ref = "tinypinyin" }
composeStableMarker = {module = "com.github.skydoves:compose-stable-marker", version.ref = "composeStableMarker"}

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-plugin" }
com-android-library = { id = "com.android.library", version.ref = "android-plugin" }
androidx-navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
mavenpublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenpublish" }
org-jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
org-jetbrains-kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

[bundles]
androidx-compose = [
    "androidx-activity-compose",
    "androidx-compose-animation",
    "androidx-compose-foundation",
    "androidx-compose-material3",
    "androidx-compose-runtime",
    "androidx-compose-ui",
    "androidx-compose-ui-tooling",
    "androidx-lifecycle-viewmodel-compose",
    "androidx-paging-compose",
    "google-accompanist-swiperefresh",
]
androidx-navigation = [
    "androidx-navigation-fragment",
    "androidx-navigation-ui",
]
androidx-paging = [
    "androidx-paging-common",
    "androidx-paging-runtime",
]
panpf-assemblyadapter4 = [
    "panpf-assemblyadapter4-pager",
    "panpf-assemblyadapter4-pager2",
    "panpf-assemblyadapter4-recycler",
    "panpf-assemblyadapter4-recycler-paging",
]
panpf-tools4a = [
    "panpf-tools4a-activity",
    "panpf-tools4a-device",
    "panpf-tools4a-display",
    "panpf-tools4a-dimen",
    "panpf-tools4a-fileprovider",
    "panpf-tools4a-network",
    "panpf-tools4a-toast",
]
panpf-tools4j = [
    "panpf-tools4j-date",
    "panpf-tools4j-math",
    "panpf-tools4j-io",
    "panpf-tools4j-security",
]
retrofit2 = [
    "retrofit2",
    "retrofit2-kotlinxSerializationConverter",
]
test = [
    "androidx-test-runner",
    "androidx-test-rules",
    "androidx-test-ext-junit",
    "junit",
    "panpf-tools4a-device",
    "panpf-tools4a-dimen",
    "panpf-tools4a-display",
    "panpf-tools4a-network",
    "panpf-tools4a-run",
    "panpf-tools4a-test",
    "panpf-tools4j-reflect",
    "panpf-tools4j-security",
    "panpf-tools4j-test",
]