name: Package

on: workflow_dispatch

jobs:
  package-android:
    name: Package android
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Run package
        run: ./gradlew samples:androidApp:assembleRelease

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-files
          path: samples/androidApp/build/outputs/apk/release/*.apk

  package-ios:
    name: Package ios
    runs-on: macos-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run package
        run: xcodebuild -project samples/iosApp/iosApp.xcodeproj -scheme iosApp -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -derivedDataPath samples/shared/build/ios/outputs/

      - name: Read version name
        id: version_name_step
        run: |
          versionName=$(grep '^versionName=' gradle.properties | awk -F'=' '{print $2}')
          echo "version_name=$versionName" >> $GITHUB_OUTPUT

      - name: File name add version
        run: mv "samples/shared/build/ios/outputs/Build/Products/Debug-iphonesimulator/Sketch4 Sample.app" "samples/shared/build/ios/outputs/Build/Products/Debug-iphonesimulator/Sketch4 Sample-${{ steps.version_name_step.outputs.version_name }}.app"

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-files
          path: samples/shared/build/ios/outputs/Build/Products/Debug-iphonesimulator/*.app

  package-linux:
    name: Package linux desktop
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run package
        run: ./gradlew samples:desktopApp:packageReleaseDeb

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deb-files
          path: samples/desktopApp/build/compose/binaries/main-release/deb/*.deb

  package-macos:
    name: Package macos desktop
    runs-on: macos-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run package
        run: ./gradlew samples:desktopApp:packageReleaseDmg

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dmg-files
          path: samples/desktopApp/build/compose/binaries/main-release/dmg/*.dmg

  package-windows:
    name: Package windows desktop
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run package
        run: ./gradlew samples:desktopApp:packageReleaseMsi

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: msi-files
          path: samples/desktopApp/build/compose/binaries/main-release/msi/*.msi

  package-js:
    name: Package js browser
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run package
        run: ./gradlew samples:jsApp:jsBrowserDistribution

      - name: Read version name
        id: version_name_step
        run: |
          versionName=$(grep '^versionName=' gradle.properties | awk -F'=' '{print $2}')
          echo "version_name=$versionName" >> $GITHUB_OUTPUT

      - name: Compress
        run: cd samples/jsApp/build/dist/js/productionExecutable; zip -r "sketch-sample-js-${{ steps.version_name_step.outputs.version_name }}.zip" *; cd -

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: js-browser-files
          path: samples/jsApp/build/dist/js/productionExecutable/*.zip

  package-wasm-js:
    name: Package wasm js browser
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run package
        run: ./gradlew samples:wasmJsApp:wasmJsBrowserDistribution

      - name: Read version name
        id: version_name_step
        run: |
          versionName=$(grep '^versionName=' gradle.properties | awk -F'=' '{print $2}')
          echo "version_name=$versionName" >> $GITHUB_OUTPUT

      - name: Compress
        run: cd samples/wasmJsApp/build/dist/wasmJs/productionExecutable; zip -r "sketch-sample-wasmJs-${{ steps.version_name_step.outputs.version_name }}.zip" *; cd -

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-js-browser-files
          path: samples/wasmJsApp/build/dist/wasmJs/productionExecutable/*.zip